version: '3.7'
services:
  notebook:
    image: tensorflow/tensorflow:1.10.1-devel-py3
    volumes:
      - type: bind
        source: .
        target: /notebooks/probability
    working_dir: /notebooks
    ports:
      - 11000:8888
    command: /run_jupyter.sh --NotebookApp.token='' --allow-root
